# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\project\TurbineTest\MergeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MergeDialog(object):
    def setupUi(self, MergeDialog):
        MergeDialog.setObjectName("MergeDialog")
        MergeDialog.resize(610, 435)
        self.m_fileListView = QtWidgets.QListView(MergeDialog)
        self.m_fileListView.setGeometry(QtCore.QRect(240, 10, 361, 371))
        self.m_fileListView.setObjectName("m_fileListView")
        self.groupBox = QtWidgets.QGroupBox(MergeDialog)
        self.groupBox.setGeometry(QtCore.QRect(110, 230, 120, 151))
        self.groupBox.setObjectName("groupBox")
        self.m_commaCheck = QtWidgets.QCheckBox(self.groupBox)
        self.m_commaCheck.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.m_commaCheck.setChecked(True)
        self.m_commaCheck.setObjectName("m_commaCheck")
        self.buttonGroup = QtWidgets.QButtonGroup(MergeDialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.m_commaCheck)
        self.m_semiCheck = QtWidgets.QCheckBox(self.groupBox)
        self.m_semiCheck.setGeometry(QtCore.QRect(10, 40, 91, 21))
        self.m_semiCheck.setObjectName("m_semiCheck")
        self.buttonGroup.addButton(self.m_semiCheck)
        self.m_spaceCheck = QtWidgets.QCheckBox(self.groupBox)
        self.m_spaceCheck.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.m_spaceCheck.setObjectName("m_spaceCheck")
        self.buttonGroup.addButton(self.m_spaceCheck)
        self.m_tabCheck = QtWidgets.QCheckBox(self.groupBox)
        self.m_tabCheck.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.m_tabCheck.setObjectName("m_tabCheck")
        self.buttonGroup.addButton(self.m_tabCheck)
        self.m_otherEdit = QtWidgets.QLineEdit(self.groupBox)
        self.m_otherEdit.setGeometry(QtCore.QRect(60, 100, 51, 20))
        self.m_otherEdit.setObjectName("m_otherEdit")
        self.m_otherCheck = QtWidgets.QCheckBox(self.groupBox)
        self.m_otherCheck.setGeometry(QtCore.QRect(10, 100, 71, 16))
        self.m_otherCheck.setObjectName("m_otherCheck")
        self.buttonGroup.addButton(self.m_otherCheck)
        self.groupBox_2 = QtWidgets.QGroupBox(MergeDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 211, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 10, 91, 16))
        self.label.setObjectName("label")
        self.m_headrowEdit = QtWidgets.QSpinBox(self.groupBox_2)
        self.m_headrowEdit.setGeometry(QtCore.QRect(140, 10, 42, 16))
        self.m_headrowEdit.setMinimum(1)
        self.m_headrowEdit.setMaximum(20)
        self.m_headrowEdit.setSingleStep(1)
        self.m_headrowEdit.setObjectName("m_headrowEdit")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 91, 16))
        self.label_2.setObjectName("label_2")
        self.m_dataStartRowEdit = QtWidgets.QSpinBox(self.groupBox_2)
        self.m_dataStartRowEdit.setGeometry(QtCore.QRect(140, 30, 42, 16))
        self.m_dataStartRowEdit.setMinimum(1)
        self.m_dataStartRowEdit.setMaximum(20)
        self.m_dataStartRowEdit.setProperty("value", 2)
        self.m_dataStartRowEdit.setObjectName("m_dataStartRowEdit")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 91, 16))
        self.label_3.setObjectName("label_3")
        self.m_XColumnEdit = QtWidgets.QSpinBox(self.groupBox_2)
        self.m_XColumnEdit.setGeometry(QtCore.QRect(140, 50, 42, 16))
        self.m_XColumnEdit.setMinimum(1)
        self.m_XColumnEdit.setMaximum(20)
        self.m_XColumnEdit.setObjectName("m_XColumnEdit")
        self.m_YStartColumnEdit = QtWidgets.QSpinBox(self.groupBox_2)
        self.m_YStartColumnEdit.setGeometry(QtCore.QRect(140, 70, 42, 16))
        self.m_YStartColumnEdit.setMinimum(1)
        self.m_YStartColumnEdit.setMaximum(20)
        self.m_YStartColumnEdit.setProperty("value", 2)
        self.m_YStartColumnEdit.setObjectName("m_YStartColumnEdit")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 91, 16))
        self.label_4.setObjectName("label_4")
        self.m_stepEdit = QtWidgets.QSpinBox(self.groupBox_2)
        self.m_stepEdit.setGeometry(QtCore.QRect(140, 90, 42, 16))
        self.m_stepEdit.setMinimum(1)
        self.m_stepEdit.setMaximum(100)
        self.m_stepEdit.setProperty("value", 1)
        self.m_stepEdit.setObjectName("m_stepEdit")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 90, 111, 20))
        self.label_5.setObjectName("label_5")
        self.m_offsetDataHeadEdit = QtWidgets.QSpinBox(self.groupBox_2)
        self.m_offsetDataHeadEdit.setGeometry(QtCore.QRect(140, 110, 42, 16))
        self.m_offsetDataHeadEdit.setMinimum(-20)
        self.m_offsetDataHeadEdit.setMaximum(20)
        self.m_offsetDataHeadEdit.setProperty("value", 0)
        self.m_offsetDataHeadEdit.setObjectName("m_offsetDataHeadEdit")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(20, 100, 121, 31))
        self.label_9.setObjectName("label_9")
        self.m_selectButton = QtWidgets.QPushButton(MergeDialog)
        self.m_selectButton.setGeometry(QtCore.QRect(120, 390, 61, 23))
        self.m_selectButton.setObjectName("m_selectButton")
        self.m_saveButton = QtWidgets.QPushButton(MergeDialog)
        self.m_saveButton.setGeometry(QtCore.QRect(250, 390, 61, 23))
        self.m_saveButton.setObjectName("m_saveButton")
        self.m_quitButton = QtWidgets.QPushButton(MergeDialog)
        self.m_quitButton.setGeometry(QtCore.QRect(390, 390, 75, 23))
        self.m_quitButton.setObjectName("m_quitButton")
        self.groupBox_3 = QtWidgets.QGroupBox(MergeDialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 330, 91, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.m_colmunSpanCheck = QtWidgets.QCheckBox(self.groupBox_3)
        self.m_colmunSpanCheck.setGeometry(QtCore.QRect(10, 10, 89, 13))
        self.m_colmunSpanCheck.setChecked(True)
        self.m_colmunSpanCheck.setObjectName("m_colmunSpanCheck")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MergeDialog)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.m_colmunSpanCheck)
        self.m_rowSpanCheck = QtWidgets.QCheckBox(self.groupBox_3)
        self.m_rowSpanCheck.setGeometry(QtCore.QRect(10, 30, 89, 13))
        self.m_rowSpanCheck.setChecked(False)
        self.m_rowSpanCheck.setObjectName("m_rowSpanCheck")
        self.buttonGroup_2.addButton(self.m_rowSpanCheck)
        self.groupBox_4 = QtWidgets.QGroupBox(MergeDialog)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 230, 91, 91))
        self.groupBox_4.setObjectName("groupBox_4")
        self.m_srcEncodingCBBox = QtWidgets.QComboBox(self.groupBox_4)
        self.m_srcEncodingCBBox.setGeometry(QtCore.QRect(9, 30, 81, 21))
        self.m_srcEncodingCBBox.setObjectName("m_srcEncodingCBBox")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label_7.setObjectName("label_7")
        self.m_destEncodingCBBox = QtWidgets.QComboBox(self.groupBox_4)
        self.m_destEncodingCBBox.setGeometry(QtCore.QRect(9, 70, 81, 21))
        self.m_destEncodingCBBox.setObjectName("m_destEncodingCBBox")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 61, 16))
        self.label_8.setObjectName("label_8")
        self.dockWidget = QtWidgets.QDockWidget(MergeDialog)
        self.dockWidget.setGeometry(QtCore.QRect(530, 80, 54, 71))
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.groupBox_5 = QtWidgets.QGroupBox(MergeDialog)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 140, 211, 81))
        self.groupBox_5.setObjectName("groupBox_5")
        self.m_XasIndexCheck = QtWidgets.QCheckBox(self.groupBox_5)
        self.m_XasIndexCheck.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.m_XasIndexCheck.setChecked(True)
        self.m_XasIndexCheck.setObjectName("m_XasIndexCheck")
        self.m_XisDateTimeCheck = QtWidgets.QCheckBox(self.groupBox_5)
        self.m_XisDateTimeCheck.setGeometry(QtCore.QRect(10, 30, 141, 16))
        self.m_XisDateTimeCheck.setChecked(True)
        self.m_XisDateTimeCheck.setObjectName("m_XisDateTimeCheck")
        self.m_datetimeFormatCBBox = QtWidgets.QComboBox(self.groupBox_5)
        self.m_datetimeFormatCBBox.setGeometry(QtCore.QRect(9, 60, 191, 21))
        self.m_datetimeFormatCBBox.setObjectName("m_datetimeFormatCBBox")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setGeometry(QtCore.QRect(10, 40, 91, 21))
        self.label_10.setObjectName("label_10")

        self.retranslateUi(MergeDialog)
        self.m_srcEncodingCBBox.setCurrentIndex(-1)
        self.m_datetimeFormatCBBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MergeDialog)

    def retranslateUi(self, MergeDialog):
        _translate = QtCore.QCoreApplication.translate
        MergeDialog.setWindowTitle(_translate("MergeDialog", "Dialog"))
        self.groupBox.setTitle(_translate("MergeDialog", "Data delimiter:"))
        self.m_commaCheck.setText(_translate("MergeDialog", ",Comma"))
        self.m_semiCheck.setText(_translate("MergeDialog", ";Semicolon"))
        self.m_spaceCheck.setText(_translate("MergeDialog", "Space"))
        self.m_tabCheck.setText(_translate("MergeDialog", "Tab"))
        self.m_otherEdit.setText(_translate("MergeDialog", ","))
        self.m_otherCheck.setText(_translate("MergeDialog", "Other"))
        self.groupBox_2.setTitle(_translate("MergeDialog", "Position setting"))
        self.label.setText(_translate("MergeDialog", "head row"))
        self.label_2.setText(_translate("MergeDialog", "data start row"))
        self.label_3.setText(_translate("MergeDialog", "X colmun"))
        self.label_4.setText(_translate("MergeDialog", "Y start colmun"))
        self.label_5.setText(_translate("MergeDialog", "Y colmun step"))
        self.label_9.setText(_translate("MergeDialog", "data col. offset from head"))
        self.m_selectButton.setText(_translate("MergeDialog", "Select"))
        self.m_saveButton.setText(_translate("MergeDialog", "Save"))
        self.m_quitButton.setText(_translate("MergeDialog", "Quit"))
        self.groupBox_3.setTitle(_translate("MergeDialog", "Merging by"))
        self.m_colmunSpanCheck.setText(_translate("MergeDialog", "column span"))
        self.m_rowSpanCheck.setText(_translate("MergeDialog", "row span"))
        self.groupBox_4.setTitle(_translate("MergeDialog", "En/Decoding Style"))
        self.label_7.setText(_translate("MergeDialog", "Source Files:"))
        self.label_8.setText(_translate("MergeDialog", "Target Files:"))
        self.groupBox_5.setTitle(_translate("MergeDialog", "Index setting"))
        self.m_XasIndexCheck.setText(_translate("MergeDialog", "X col. as index"))
        self.m_XisDateTimeCheck.setText(_translate("MergeDialog", "X col. is DateTime Type"))
        self.label_10.setText(_translate("MergeDialog", "DateTime Format:"))

