# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyDataSetting.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DataSettingDialog(object):
    def setupUi(self, DataSettingDialog):
        DataSettingDialog.setObjectName("DataSettingDialog")
        DataSettingDialog.resize(677, 371)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DataSettingDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(DataSettingDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.DataSetting = QtWidgets.QWidget()
        self.DataSetting.setObjectName("DataSetting")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.DataSetting)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 652, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.groupBox_3 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.RadioFromFile = QtWidgets.QRadioButton(self.groupBox_3)
        self.RadioFromFile.setGeometry(QtCore.QRect(50, 0, 51, 16))
        self.RadioFromFile.setChecked(True)
        self.RadioFromFile.setObjectName("RadioFromFile")
        self.RadioUserDefine = QtWidgets.QRadioButton(self.groupBox_3)
        self.RadioUserDefine.setGeometry(QtCore.QRect(0, 0, 41, 16))
        self.RadioUserDefine.setObjectName("RadioUserDefine")
        self.horizontalLayout_10.addWidget(self.groupBox_3)
        self.BTNFromFile = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.BTNFromFile.setAutoFillBackground(False)
        self.BTNFromFile.setAutoDefault(True)
        self.BTNFromFile.setFlat(False)
        self.BTNFromFile.setObjectName("BTNFromFile")
        self.horizontalLayout_10.addWidget(self.BTNFromFile)
        self.EditFileName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.EditFileName.setEnabled(False)
        self.EditFileName.setAutoFillBackground(False)
        self.EditFileName.setObjectName("EditFileName")
        self.horizontalLayout_10.addWidget(self.EditFileName)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 3)
        self.horizontalLayout_10.setStretch(2, 1)
        self.horizontalLayout_10.setStretch(3, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.SpinHeadStart = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.SpinHeadStart.setMinimum(1)
        self.SpinHeadStart.setMaximum(1000)
        self.SpinHeadStart.setProperty("value", 1)
        self.SpinHeadStart.setObjectName("SpinHeadStart")
        self.horizontalLayout_9.addWidget(self.SpinHeadStart)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.SpinDataStart = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.SpinDataStart.setMinimum(1)
        self.SpinDataStart.setMaximum(1000)
        self.SpinDataStart.setProperty("value", 2)
        self.SpinDataStart.setObjectName("SpinDataStart")
        self.horizontalLayout_9.addWidget(self.SpinDataStart)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_9.addWidget(self.label_17)
        self.SpinMaxRow = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.SpinMaxRow.setMaximum(3000000)
        self.SpinMaxRow.setSingleStep(100)
        self.SpinMaxRow.setProperty("value", 3000000)
        self.SpinMaxRow.setObjectName("SpinMaxRow")
        self.horizontalLayout_9.addWidget(self.SpinMaxRow)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.CBoxDelimiter = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.CBoxDelimiter.setObjectName("CBoxDelimiter")
        self.CBoxDelimiter.addItem("")
        self.CBoxDelimiter.addItem("")
        self.CBoxDelimiter.addItem("")
        self.CBoxDelimiter.addItem("")
        self.horizontalLayout_9.addWidget(self.CBoxDelimiter)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_9.addWidget(self.label_18)
        self.CBoxEncoding = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.CBoxEncoding.setObjectName("CBoxEncoding")
        self.CBoxEncoding.addItem("")
        self.CBoxEncoding.addItem("")
        self.CBoxEncoding.addItem("")
        self.CBoxEncoding.addItem("")
        self.CBoxEncoding.addItem("")
        self.CBoxEncoding.addItem("")
        self.CBoxEncoding.addItem("")
        self.CBoxEncoding.addItem("")
        self.CBoxEncoding.addItem("")
        self.CBoxEncoding.addItem("")
        self.horizontalLayout_9.addWidget(self.CBoxEncoding)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16)
        self.CBoxTimeFormat = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.CBoxTimeFormat.setObjectName("CBoxTimeFormat")
        self.CBoxTimeFormat.addItem("")
        self.CBoxTimeFormat.addItem("")
        self.CBoxTimeFormat.addItem("")
        self.CBoxTimeFormat.addItem("")
        self.CBoxTimeFormat.addItem("")
        self.CBoxTimeFormat.addItem("")
        self.CBoxTimeFormat.addItem("")
        self.CBoxTimeFormat.addItem("")
        self.CBoxTimeFormat.addItem("")
        self.CBoxTimeFormat.addItem("")
        self.CBoxTimeFormat.addItem("")
        self.CBoxTimeFormat.addItem("")
        self.CBoxTimeFormat.addItem("")
        self.CBoxTimeFormat.addItem("")
        self.CBoxTimeFormat.addItem("")
        self.CBoxTimeFormat.addItem("")
        self.horizontalLayout_9.addWidget(self.CBoxTimeFormat)
        self.horizontalLayout_9.setStretch(0, 4)
        self.horizontalLayout_9.setStretch(1, 5)
        self.horizontalLayout_9.setStretch(2, 4)
        self.horizontalLayout_9.setStretch(3, 5)
        self.horizontalLayout_9.setStretch(4, 4)
        self.horizontalLayout_9.setStretch(5, 8)
        self.horizontalLayout_9.setStretch(6, 3)
        self.horizontalLayout_9.setStretch(7, 1)
        self.horizontalLayout_9.setStretch(8, 3)
        self.horizontalLayout_9.setStretch(9, 3)
        self.horizontalLayout_9.setStretch(10, 3)
        self.horizontalLayout_9.setStretch(11, 20)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.CBoxXCol = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.CBoxXCol.setObjectName("CBoxXCol")
        self.horizontalLayout_6.addWidget(self.CBoxXCol)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.CBoxXType = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.CBoxXType.setObjectName("CBoxXType")
        self.CBoxXType.addItem("")
        self.CBoxXType.addItem("")
        self.CBoxXType.addItem("")
        self.CBoxXType.addItem("")
        self.CBoxXType.addItem("")
        self.horizontalLayout_6.addWidget(self.CBoxXType)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.EditXmin = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.EditXmin.setObjectName("EditXmin")
        self.horizontalLayout_6.addWidget(self.EditXmin)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.EditXmax = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.EditXmax.setObjectName("EditXmax")
        self.horizontalLayout_6.addWidget(self.EditXmax)
        self.horizontalLayout_6.setStretch(0, 6)
        self.horizontalLayout_6.setStretch(1, 12)
        self.horizontalLayout_6.setStretch(2, 3)
        self.horizontalLayout_6.setStretch(3, 6)
        self.horizontalLayout_6.setStretch(4, 4)
        self.horizontalLayout_6.setStretch(5, 6)
        self.horizontalLayout_6.setStretch(6, 1)
        self.horizontalLayout_6.setStretch(7, 6)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.BTNSelectYs = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.BTNSelectYs.setObjectName("BTNSelectYs")
        self.horizontalLayout_5.addWidget(self.BTNSelectYs)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.CBoxYCols = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.CBoxYCols.setObjectName("CBoxYCols")
        self.horizontalLayout_5.addWidget(self.CBoxYCols)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.CBoxYType = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.CBoxYType.setObjectName("CBoxYType")
        self.CBoxYType.addItem("")
        self.CBoxYType.addItem("")
        self.CBoxYType.addItem("")
        self.horizontalLayout_5.addWidget(self.CBoxYType)
        self.horizontalLayout_5.setStretch(0, 6)
        self.horizontalLayout_5.setStretch(1, 3)
        self.horizontalLayout_5.setStretch(2, 1)
        self.horizontalLayout_5.setStretch(3, 20)
        self.horizontalLayout_5.setStretch(4, 1)
        self.horizontalLayout_5.setStretch(5, 3)
        self.horizontalLayout_5.setStretch(6, 6)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(6, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(7, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 7, item)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 9)
        self.tabWidget.addTab(self.DataSetting, "")
        self.FigureSetting = QtWidgets.QWidget()
        self.FigureSetting.setObjectName("FigureSetting")
        self.tabWidget.addTab(self.FigureSetting, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.buttonBox = QtWidgets.QDialogButtonBox(DataSettingDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(DataSettingDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(DataSettingDialog.accept)
        self.buttonBox.rejected.connect(DataSettingDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(DataSettingDialog)

    def retranslateUi(self, DataSettingDialog):
        _translate = QtCore.QCoreApplication.translate
        DataSettingDialog.setWindowTitle(_translate("DataSettingDialog", "Setting"))
        self.label_8.setText(_translate("DataSettingDialog", "数据来源"))
        self.RadioFromFile.setText(_translate("DataSettingDialog", "来自文件"))
        self.RadioUserDefine.setText(_translate("DataSettingDialog", "自定义"))
        self.BTNFromFile.setText(_translate("DataSettingDialog", "选择文件"))
        self.EditFileName.setText(_translate("DataSettingDialog", "E:\\mydoucument\\data.csv"))
        self.label_13.setText(_translate("DataSettingDialog", "字头开始行"))
        self.label_14.setText(_translate("DataSettingDialog", "数据开始行"))
        self.label_17.setText(_translate("DataSettingDialog", "最大读取行"))
        self.label_15.setText(_translate("DataSettingDialog", "分隔符"))
        self.CBoxDelimiter.setItemText(0, _translate("DataSettingDialog", ","))
        self.CBoxDelimiter.setItemText(1, _translate("DataSettingDialog", ";"))
        self.CBoxDelimiter.setItemText(2, _translate("DataSettingDialog", "tab"))
        self.CBoxDelimiter.setItemText(3, _translate("DataSettingDialog", "space"))
        self.label_18.setText(_translate("DataSettingDialog", "encoding"))
        self.CBoxEncoding.setItemText(0, _translate("DataSettingDialog", "gb2312"))
        self.CBoxEncoding.setItemText(1, _translate("DataSettingDialog", "utf_16"))
        self.CBoxEncoding.setItemText(2, _translate("DataSettingDialog", "latin_1"))
        self.CBoxEncoding.setItemText(3, _translate("DataSettingDialog", "cp65001"))
        self.CBoxEncoding.setItemText(4, _translate("DataSettingDialog", "ascii"))
        self.CBoxEncoding.setItemText(5, _translate("DataSettingDialog", "utf_8"))
        self.CBoxEncoding.setItemText(6, _translate("DataSettingDialog", "gb18030"))
        self.CBoxEncoding.setItemText(7, _translate("DataSettingDialog", "gbk"))
        self.CBoxEncoding.setItemText(8, _translate("DataSettingDialog", "big5"))
        self.CBoxEncoding.setItemText(9, _translate("DataSettingDialog", "big5hkscs"))
        self.label_16.setText(_translate("DataSettingDialog", "时间格式"))
        self.CBoxTimeFormat.setItemText(0, _translate("DataSettingDialog", "yyyy/mm/dd hh:mm:ss"))
        self.CBoxTimeFormat.setItemText(1, _translate("DataSettingDialog", "yyyy/mm/dd h:m:s"))
        self.CBoxTimeFormat.setItemText(2, _translate("DataSettingDialog", "yyyy/mm/dd hh:mm"))
        self.CBoxTimeFormat.setItemText(3, _translate("DataSettingDialog", "yyyy/mm/dd h:m"))
        self.CBoxTimeFormat.setItemText(4, _translate("DataSettingDialog", "yy/mm/dd hh:mm:ss"))
        self.CBoxTimeFormat.setItemText(5, _translate("DataSettingDialog", "yy/mm/dd h:m:s"))
        self.CBoxTimeFormat.setItemText(6, _translate("DataSettingDialog", "yy/mm/dd hh:mm"))
        self.CBoxTimeFormat.setItemText(7, _translate("DataSettingDialog", "yy/mm/dd h:m"))
        self.CBoxTimeFormat.setItemText(8, _translate("DataSettingDialog", "yyyy-mm-dd hh:mm:ss"))
        self.CBoxTimeFormat.setItemText(9, _translate("DataSettingDialog", "yyyy-mm-dd h:m:s"))
        self.CBoxTimeFormat.setItemText(10, _translate("DataSettingDialog", "yyyy-mm-dd hh:mm"))
        self.CBoxTimeFormat.setItemText(11, _translate("DataSettingDialog", "yyyy-mm-dd h:m"))
        self.CBoxTimeFormat.setItemText(12, _translate("DataSettingDialog", "yy-mm-dd hh:mm:ss"))
        self.CBoxTimeFormat.setItemText(13, _translate("DataSettingDialog", "yy-mm-dd h:m:s"))
        self.CBoxTimeFormat.setItemText(14, _translate("DataSettingDialog", "yy-mm-dd hh:mm"))
        self.CBoxTimeFormat.setItemText(15, _translate("DataSettingDialog", "yy-mm-dd h:m"))
        self.label_7.setText(_translate("DataSettingDialog", "X轴取自文件哪列？"))
        self.label_3.setText(_translate("DataSettingDialog", "X轴类型"))
        self.CBoxXType.setItemText(0, _translate("DataSettingDialog", "实数"))
        self.CBoxXType.setItemText(1, _translate("DataSettingDialog", "日期"))
        self.CBoxXType.setItemText(2, _translate("DataSettingDialog", "时间"))
        self.CBoxXType.setItemText(3, _translate("DataSettingDialog", "日期时间"))
        self.CBoxXType.setItemText(4, _translate("DataSettingDialog", "散点"))
        self.label_4.setText(_translate("DataSettingDialog", "X轴范围,从"))
        self.label_5.setText(_translate("DataSettingDialog", "到"))
        self.label_9.setText(_translate("DataSettingDialog", "Y轴取自文件哪几列？"))
        self.BTNSelectYs.setText(_translate("DataSettingDialog", "选择"))
        self.label_10.setText(_translate("DataSettingDialog", "第"))
        self.label_11.setText(_translate("DataSettingDialog", "列"))
        self.label_6.setText(_translate("DataSettingDialog", "Y轴类型"))
        self.CBoxYType.setItemText(0, _translate("DataSettingDialog", "实数"))
        self.CBoxYType.setItemText(1, _translate("DataSettingDialog", "振幅@相角"))
        self.CBoxYType.setItemText(2, _translate("DataSettingDialog", "振奋∠相角"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("DataSettingDialog", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("DataSettingDialog", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("DataSettingDialog", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("DataSettingDialog", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("DataSettingDialog", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("DataSettingDialog", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("DataSettingDialog", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("DataSettingDialog", "8"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DataSettingDialog", "系列名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DataSettingDialog", "f(x)"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DataSettingDialog", "下限"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("DataSettingDialog", "上限"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("DataSettingDialog", "可见"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("DataSettingDialog", "颜色"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("DataSettingDialog", "线宽"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("DataSettingDialog", "线形"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("DataSettingDialog", "1"))
        item = self.tableWidget.item(1, 6)
        item.setText(_translate("DataSettingDialog", "1"))
        item = self.tableWidget.item(2, 6)
        item.setText(_translate("DataSettingDialog", "1"))
        item = self.tableWidget.item(3, 6)
        item.setText(_translate("DataSettingDialog", "1"))
        item = self.tableWidget.item(4, 6)
        item.setText(_translate("DataSettingDialog", "1"))
        item = self.tableWidget.item(5, 6)
        item.setText(_translate("DataSettingDialog", "1"))
        item = self.tableWidget.item(6, 6)
        item.setText(_translate("DataSettingDialog", "1"))
        item = self.tableWidget.item(7, 6)
        item.setText(_translate("DataSettingDialog", "1"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DataSetting), _translate("DataSettingDialog", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FigureSetting), _translate("DataSettingDialog", "Tab 2"))

